### PR TITLE
Export isEqual helper and improve type definitions

### LINKED ISSUE #7: paylaod typo
it's payload, not paylaod

https://github.com/schettino/react-request-hook/blob/7a7da5cfa60da589cef342729bd55c3eba38b5d5/src/request.ts#L39

### LINKED ISSUE #11: Why to use null for data/error keys?
The topic about these two lines and some logic beneath them:

https://github.com/schettino/react-request-hook/blob/7a7da5cfa60da589cef342729bd55c3eba38b5d5/src/useResource.ts#L17-L18

It's already may be `undefined`. It should be sufficient to use `undefined`. Why should we make it `null` and/or place `null` there? (Do you remember the joke about the billion dollar mistake?)

### LINKED ISSUE #13: Can't start the project
I wanted to play a bit with these [null/undefined](https://github.com/schettino/react-request-hook/issues/11), so I cloned the repo but after `yarn && yarn start` I've encountered two problems:

### First problem

```
rollup v0.66.6
bundles src/index.ts → dist/index.js, dist/index.es.js...
rpt2: options error TS5053 Option 'declaration' cannot be specified with option 'isolatedModules'.
created dist/index.js, dist/index.es.js in 2.7s

[2019-05-06 18:16:37] waiting for changes...
```

However, by "waiting for changes" I suppose it's working anyway...

### Second problem

I use the lib in my project - it's working ok. I managed to switch to my local `react-request-hook` with `yarn link` the lib, then `yarn link react-request-hook` in my project, but then I get this error in my app:

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I tried to disable `declaration` and `isolatedModules` - it doesn't help, so it looks like these are different problems

### Just a note

Also, you use `allowSyntheticDefaultImports` and `esModuleInterop` at the same time - but `allowSyntheticDefaultImports` may be disabled ([here's why](https://github.com/Microsoft/TypeScript/pull/26866/commits/aaa723e2d2ee393331ac9d8eba29d66b80f415fe))

### Additional thoughts

I may miss something. Maybe it's good idea to place some "How to contribute" section in readme

### PR DESCRIPTION
**Pull request by schettino**
This PR improves the type definition for the `data` and `error` values. Until now, these properties have had as possible types `null` and `undefined`, which could add a bit of verbosity when interacting with them. The only options now are the actual value these properties can receive or `undefined`, making type definitions around them more straightforward.

The `isEqual` helper has been exported so it can be used to perform comparisons when calling the `request` method programatically. 

Last but not least, we now have the /example folder as a project we can easily run during development. The actual example (with react-request-hook from npm) that can run through Codesandbox, has been moved to its [own repo](https://github.com/schettino/react-request-hook-examples).

fix #11, fix #7, fix #13

### CODE REVIEW

**Comment by JerryGreen** [comment]
Please read this message before merging this:

https://github.com/schettino/react-request-hook/issues/11#issuecomment-489621001

undefined is better than null

**Comment by schettino** [comment]
Thanks for your feedback @JerryGreen, hopefully we're all set now.

**Comment by JerryGreen** [comment]
@schettino yea, this looks good now :)

**Pull request merged**
